language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

before_script:
  - npm i npm@latest -g
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

cache:
  directories:
    - $HOME/.npm

notifications:
  webhooks:
    - https://outlook.office.com/webhook/35c21aff-9cde-45a2-833a-d0aef9e7ca4a@dea6e02c-702b-45bc-9c84-c62f18599043/TravisCI/21fe98f8a1634dbc8b8f6770979701bb/1cdb000a-6c7b-49f2-885f-de5cf9e238cf